set positional-arguments

init:
    cargo install cargo-insta

run *args='':
    cargo run -- "$@"

test:
    cargo insta test --review
    cargo insta test --unreferenced reject

build:
    cargo build --verbose

clippy:
    cargo clippy --all-targets --all-features -- -D warnings

clippy-fix *args='':
    cargo clippy --fix $@

ci-fmt:
    cargo fmt --all -- --check

ci-test:
    cargo insta test
    cargo insta test --unreferenced reject
