name: build-and-run-tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: compiler

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Just
        run: cargo install just
      - name: Build
        run: cargo build --verbose
      - name: Initialize setup
        run: just init
      - name: Run tests
        run: cargo insta test
